# Generated by Django 5.1.6 on 2025-02-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0014_remove_comment_username_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
