# Generated by Django 5.1.6 on 2025-03-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0019_alter_chatmessage_id_alter_chatmessage_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_comments',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
