# Generated by Django 5.1.6 on 2025-03-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0020_post_no_of_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='no_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
