# Generated by Django 5.1.6 on 2025-03-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0022_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
